---
collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.aws
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhatinsights.insights
  - name: community.hashi_vault
  - name: community.crypto
  - name: community.general

roles:
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-node-exporter"
    scm: git
    version: main
    name: node_exporter
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-basyx-server"
    scm: git
    version: main
    name: basyx_server
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-consul"
    scm: git
    version: main
    name: consul