name: Build

on:
  push:
    branches:
      - main

jobs:
  build-and-push-awx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build AWX
        env:
          AWX_VERSION: 22.7.0
          DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/awx/base:${{AWX_VERSION}}
        run: |
          echo "Building AWX ${{AWX_VERSION}} as Docker Image '$DOCKER_IMAGE'"
          cd awx
          docker build --build-arg ANSIBLE_AWX_GIT_TAG=${{AWX_VERSION}} -t awx-builder:latest .
          docker run --name awx-builder -v /var/run/docker.sock:/var/run/docker.sock -e "ANSIBLE_AWX_GIT_TAG=${{AWX_VERSION}}" --rm awx-builder:latest
          docker tag awx_devel:head $DOCKER_IMAGE
          docker push $DOCKER_IMAGE
      - name: Build AWX Redis
        env:
          DOCKER_IMAGE: ghcr.io/eclipse-slm/awx/redis:6
        run: |
          cd awx-redis
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
  build-and-push-awx-ee-slm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build AWX-EE
        env:
          DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/awx-ee-slm
        run: |
          echo "Building custom AWX-EE-SLM "
          cd awx-ee-slm
          docker build -t awx-ee-slm-builder:latest .
           docker run --name awx-ee-slm-builder -v /var/run/docker.sock:/var/run/docker.sock  --rm awx-ee-slm-builder:latest
          docker tag awx_ee_slm_devel:latest $DOCKER_IMAGE
          docker push $DOCKER_IMAGE